version: '3.9'
services:
  sorteo-back:
    image: mongo:5
    container_name: sorteo-back
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
